/** Lightweight curated list — safe to import from search without pulling ingest/sql. */
export const CURATED_CLASSICS = [
  { id: 1342, title: 'Pride and Prejudice', author: 'Jane Austen', subjects: ['Romance', 'England -- Fiction'] },
  { id: 84, title: 'Frankenstein; Or, The Modern Prometheus', author: 'Mary Wollstonecraft Shelley', subjects: ['Science fiction', 'Horror'] },
  { id: 2701, title: 'Moby Dick; Or, The Whale', author: 'Herman Melville', subjects: ['Adventure', 'Sea stories'] },
  { id: 98, title: 'A Tale of Two Cities', author: 'Charles Dickens', subjects: ['Historical fiction', 'France -- Fiction'] },
  { id: 11, title: 'Alice in Wonderland', author: 'Lewis Carroll', subjects: ['Fantasy', 'Juvenile literature'] },
  { id: 1661, title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', subjects: ['Mystery', 'Detective'] },
  { id: 345, title: 'Dracula', author: 'Bram Stoker', subjects: ['Horror', 'Vampires'] },
  { id: 174, title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', subjects: ['Fiction'] },
  { id: 76, title: 'Adventures of Huckleberry Finn', author: 'Mark Twain', subjects: ['Adventure', 'Bildungsroman'] },
  { id: 5200, title: 'Metamorphosis', author: 'Franz Kafka', subjects: ['Fiction'] },
  { id: 2554, title: 'Crime and Punishment', author: 'Fyodor Dostoyevsky', subjects: ['Psychological fiction', 'Crime'] },
  { id: 120, title: 'Treasure Island', author: 'Robert Louis Stevenson', subjects: ['Adventure', 'Pirates'] },
  { id: 158, title: 'Emma', author: 'Jane Austen', subjects: ['Romance', 'England -- Fiction'] },
  { id: 259, title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne', subjects: ['Historical fiction', 'Puritans'] },
  { id: 1400, title: 'Great Expectations', author: 'Charles Dickens', subjects: ['Bildungsroman', 'England -- Fiction'] },
  { id: 46, title: 'A Christmas Carol', author: 'Charles Dickens', subjects: ['Ghost stories', 'Christmas'] },
  { id: 140, title: 'Jane Eyre', author: 'Charlotte Brontë', subjects: ['Romance', 'Gothic fiction'] },
  { id: 768, title: 'Wuthering Heights', author: 'Emily Brontë', subjects: ['Romance', 'Gothic fiction'] },
  { id: 1952, title: 'The Yellow Wallpaper', author: 'Charlotte Perkins Gilman', subjects: ['Psychological fiction', 'Horror'] },
  { id: 2600, title: 'War and Peace', author: 'Leo Tolstoy', subjects: ['Historical fiction', 'War stories'] },
  { id: 996, title: 'Don Quixote', author: 'Miguel de Cervantes', subjects: ['Adventure', 'Satire'] },
  { id: 1184, title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', subjects: ['Adventure', 'Revenge'] },
  { id: 161, title: 'Sense and Sensibility', author: 'Jane Austen', subjects: ['Romance', 'England -- Fiction'] },
  { id: 121, title: 'Northanger Abbey', author: 'Jane Austen', subjects: ['Romance', 'Gothic fiction'] },
  { id: 514, title: 'Little Women', author: 'Louisa May Alcott', subjects: ['Romance', 'Young adult'] },
  { id: 219, title: 'Heart of Darkness', author: 'Joseph Conrad', subjects: ['Fiction', 'Psychological fiction'] },
  { id: 14591, title: 'Middlemarch', author: 'George Eliot', subjects: ['Fiction', 'England -- Fiction'] },
  { id: 135, title: 'Les Misérables', author: 'Victor Hugo', subjects: ['Historical fiction', 'France -- Fiction'] },
  { id: 1727, title: 'The Odyssey', author: 'Homer', subjects: ['Epic poetry', 'Adventure'] },
  { id: 986, title: 'Bleak House', author: 'Charles Dickens', subjects: ['Fiction', 'England -- Fiction'] },
] as const
